apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: payment-gateway
          image: quay.io/acaglio/payment-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "redpanda:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "payment-gateway-group"
            - name: GRPC_CLIENT_ACCOUNT_VERIFIER_ADDRESS
              value: "static://account-verifier:9090"
            - name: GRPC_CLIENT_ACCOUNT_VERIFIER_NEGOTIATION_TYPE
              value: "plaintext"
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
