apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
  namespace: showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
        - name: payment-gateway
          image: quay.io/acaglio/payment-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/otel/opentelemetry-javaagent.jar"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
            - name: OTEL_SERVICE_NAME
              value: "payment-gateway"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "redpanda:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "payment-gateway-group"
            - name: GRPC_CLIENT_ACCOUNT_VERIFIER_ADDRESS
              value: "static://account-verifier:9090"
            - name: GRPC_CLIENT_ACCOUNT_VERIFIER_NEGOTIATION_TYPE
              value: "plaintext"
            - name: SERVER_PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
