apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.adminUsername }}
  password: {{ .Values.keycloak.adminPassword }}
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  instances: {{ .Values.keycloak.instances }}
  db:
    vendor: dev-file
  hostname:
    hostname: keycloak.{{ .Values.clusterDomain }}
  ingress:
    className: openshift-default
  bootstrapAdminUsername:
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-secret
        key: username
  bootstrapAdminPassword:
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-secret
        key: password
