apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibmmq-data
  namespace: showcase
  labels:
    app: ibmmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
