apiVersion: v1
kind: Service
metadata:
  name: ibmmq
  namespace: showcase
  labels:
    app: ibmmq
spec:
  type: ClusterIP
  selector:
    app: ibmmq
  ports:
    - name: mq
      port: 1414
      targetPort: 1414
      protocol: TCP
    - name: webconsole
      port: 9443
      targetPort: 9443
      protocol: TCP
