spring:
  application:
    name: payment-gateway
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:payment-gateway-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

grpc:
  client:
    account-verifier:
      address: ${GRPC_CLIENT_ACCOUNT_VERIFIER_ADDRESS:static://localhost:9090}
      negotiation-type: plaintext

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${SERVER_PORT:8080}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
  grpc:
    account-verifier-timeout-seconds: ${GRPC_ACCOUNT_VERIFIER_TIMEOUT_SECONDS:5}
  kafka:
    topics:
      payment-completed: ${APP_KAFKA_TOPICS_PAYMENT_COMPLETED:payment-completed}
      payment-completed-dlt: ${APP_KAFKA_TOPICS_PAYMENT_COMPLETED_DLT:payment-completed.DLT}
