apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: showcase
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespassword
  POSTGRES_DB: postgres
